CREATE TABLE dental_records (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(50) NOT NULL,
    event VARCHAR2(100) NOT NULL
);

INSERT INTO dental_records (title, event) VALUES ('Consulta Odontológica', 'Realizada em 01/11/2024');
